export type ProdesModel = {
  id: number | string;
  codigo: string;
  descricao: string;
  tipo: string;
  incidencias: string[];
  automatico: boolean;
  ativo: boolean;
};

export const MOCK_PRODES: ProdesModel[] = [
  {
    id: 1,
    codigo: 'P001',
    descricao: 'Salário Base',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 2,
    codigo: 'D001',
    descricao: 'INSS Mensal',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 3,
    codigo: 'P015',
    descricao: 'Hora Extra 50%',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 4,
    codigo: 'D042',
    descricao: 'Falta Injustificada',
    tipo: 'Desconto',
    incidencias: ['Dedução INSS', 'Dedução FGTS'],
    automatico: false,
    ativo: true,
  },
  {
    id: 5,
    codigo: 'P008',
    descricao: 'Adicional de Periculosidade',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 6,
    codigo: 'D010',
    descricao: 'Vale Transporte (6%)',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 7,
    codigo: 'P022',
    descricao: 'Gratificação por Função',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 8,
    codigo: 'P030',
    descricao: 'Auxílio Creche',
    tipo: 'Provento',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 9,
    codigo: 'D005',
    descricao: 'IRRF Mensal',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 10,
    codigo: 'P012',
    descricao: 'DSR sobre Horas Extras',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 11,
    codigo: 'D088',
    descricao: 'Empréstimo Consignado',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 12,
    codigo: 'P055',
    descricao: 'Prêmio Assiduidade',
    tipo: 'Provento',
    incidencias: ['FGTS'],
    automatico: true,
    ativo: true,
  },
  {
    id: 13,
    codigo: 'D015',
    descricao: 'Coparticipação Plano de Saúde',
    tipo: 'Desconto',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 14,
    codigo: 'P005',
    descricao: 'Adicional Noturno',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 15,
    codigo: 'P080',
    descricao: 'Salário Família',
    tipo: 'Provento',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 16,
    codigo: 'D025',
    descricao: 'Aviso Prévio Indenizado',
    tipo: 'Desconto',
    incidencias: [],
    automatico: false,
    ativo: false,
  },
  {
    id: 17,
    codigo: 'P100',
    descricao: 'Comissões de Vendas',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 18,
    codigo: 'D012',
    descricao: 'Contribuição Sindical',
    tipo: 'Desconto',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 19,
    codigo: 'P009',
    descricao: 'Adicional de Insalubridade',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 20,
    codigo: 'P200',
    descricao: 'Participação nos Lucros (PLR)',
    tipo: 'Provento',
    incidencias: ['IRRF (Tabela Exclusiva)'],
    automatico: false,
    ativo: true,
  },
  {
    id: 21,
    codigo: 'D090',
    descricao: 'Pensão Alimentícia',
    tipo: 'Desconto',
    incidencias: ['Dedução IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 22,
    codigo: 'P016',
    descricao: 'Hora Extra 100%',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 23,
    codigo: 'D003',
    descricao: 'Atrasos em Minutos',
    tipo: 'Desconto',
    incidencias: ['Dedução INSS', 'Dedução FGTS'],
    automatico: true,
    ativo: true,
  },
  {
    id: 24,
    codigo: 'P040',
    descricao: 'Quebra de Caixa',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 25,
    codigo: 'D050',
    descricao: 'Vale Refeição (Desconto)',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 26,
    codigo: 'P060',
    descricao: 'Triênio',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 27,
    codigo: 'P061',
    descricao: 'Quinquênio',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 28,
    codigo: 'D066',
    descricao: 'Estorno de Salário',
    tipo: 'Desconto',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 29,
    codigo: 'P070',
    descricao: 'Ajuda de Custo (Não Salarial)',
    tipo: 'Provento',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 30,
    codigo: 'P088',
    descricao: '13º Salário (1ª Parcela)',
    tipo: 'Provento',
    incidencias: ['FGTS'],
    automatico: false,
    ativo: true,
  },
  {
    id: 31,
    codigo: 'P089',
    descricao: '13º Salário (2ª Parcela)',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 32,
    codigo: 'D033',
    descricao: 'Adiantamento de Salário',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 33,
    codigo: 'P300',
    descricao: 'Férias Gozadas',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 34,
    codigo: 'P301',
    descricao: 'Terço Constitucional de Férias',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 35,
    codigo: 'D300',
    descricao: 'Adiantamento de Férias',
    tipo: 'Desconto',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 36,
    codigo: 'P400',
    descricao: 'Abono Pecuniário',
    tipo: 'Provento',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 37,
    codigo: 'P401',
    descricao: '1/3 Abono Pecuniário',
    tipo: 'Provento',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 38,
    codigo: 'P018',
    descricao: 'Hora Extra 70%',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 39,
    codigo: 'D018',
    descricao: 'DSR sobre Faltas',
    tipo: 'Desconto',
    incidencias: ['INSS', 'FGTS'],
    automatico: true,
    ativo: true,
  },
  {
    id: 40,
    codigo: 'P002',
    descricao: 'Complemento Salarial',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 41,
    codigo: 'D070',
    descricao: 'Mensalidade Associação',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 42,
    codigo: 'P050',
    descricao: 'Diárias para Viagem (>50%)',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 43,
    codigo: 'P051',
    descricao: 'Diárias para Viagem (<50%)',
    tipo: 'Provento',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 44,
    codigo: 'D040',
    descricao: 'Falta Meio Período',
    tipo: 'Desconto',
    incidencias: ['INSS', 'FGTS'],
    automatico: false,
    ativo: true,
  },
  {
    id: 45,
    codigo: 'P110',
    descricao: 'Bônus por Metas',
    tipo: 'Provento',
    incidencias: ['FGTS'],
    automatico: false,
    ativo: true,
  },
  {
    id: 46,
    codigo: 'D110',
    descricao: 'Previdência Privada',
    tipo: 'Desconto',
    incidencias: ['Dedução IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 47,
    codigo: 'P013',
    descricao: 'DSR sobre Comissões',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 48,
    codigo: 'P095',
    descricao: 'Estágio (Bolsa Auxílio)',
    tipo: 'Provento',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 49,
    codigo: 'D095',
    descricao: 'Seguro de Vida (Funcionário)',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 50,
    codigo: 'P003',
    descricao: 'Diferença Salarial Retroativa',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 51,
    codigo: 'P120',
    descricao: 'Adicional de Transferência',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 52,
    codigo: 'D020',
    descricao: 'Convênio Farmácia',
    tipo: 'Desconto',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 53,
    codigo: 'P017',
    descricao: 'Hora Extra Interjornada',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 54,
    codigo: 'P019',
    descricao: 'Hora de Sobreaviso',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 55,
    codigo: 'D080',
    descricao: 'Danos Causados pelo Empregado',
    tipo: 'Desconto',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 56,
    codigo: 'P150',
    descricao: 'Salário Maternidade',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 57,
    codigo: 'P160',
    descricao: 'Auxílio Doença (15 dias)',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 58,
    codigo: 'D009',
    descricao: 'Vale Cultura (Desconto)',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 59,
    codigo: 'P035',
    descricao: 'Reembolso de Despesas',
    tipo: 'Provento',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 60,
    codigo: 'D060',
    descricao: 'Empréstimo Empresa',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 61,
    codigo: 'P011',
    descricao: 'Gratificação de Balanço',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 62,
    codigo: 'P014',
    descricao: 'Hora Extra Noturna 50%',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 63,
    codigo: 'P025',
    descricao: 'Anuênio',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 64,
    codigo: 'D004',
    descricao: 'Arredondamento Anterior',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 65,
    codigo: 'P004',
    descricao: 'Arredondamento Atual',
    tipo: 'Provento',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 66,
    codigo: 'P081',
    descricao: 'Salário Família Retroativo',
    tipo: 'Provento',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 67,
    codigo: 'D014',
    descricao: 'Contribuição Assistencial',
    tipo: 'Desconto',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 68,
    codigo: 'P500',
    descricao: 'Saldo de Salário (Rescisão)',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 69,
    codigo: 'P501',
    descricao: 'Férias Proporcionais (Rescisão)',
    tipo: 'Provento',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 70,
    codigo: 'P502',
    descricao: '13º Salário Proporcional (Rescisão)',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 71,
    codigo: 'D500',
    descricao: 'Aviso Prévio Trabalhado (Desconto)',
    tipo: 'Desconto',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 72,
    codigo: 'P503',
    descricao: 'Indenização Art 479 CLT',
    tipo: 'Provento',
    incidencias: ['FGTS'],
    automatico: false,
    ativo: true,
  },
  {
    id: 73,
    codigo: 'P504',
    descricao: 'Férias Vencidas (Rescisão)',
    tipo: 'Provento',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 74,
    codigo: 'D101',
    descricao: 'Estorno de Comissões',
    tipo: 'Desconto',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 75,
    codigo: 'P045',
    descricao: 'Auxílio Moradia',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 76,
    codigo: 'P046',
    descricao: 'Gratificação Semestral',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 77,
    codigo: 'D011',
    descricao: 'Vale Estacionamento (Desconto)',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 78,
    codigo: 'P020',
    descricao: 'Adicional por Tempo de Serviço',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 79,
    codigo: 'P021',
    descricao: 'Quebra de Material',
    tipo: 'Provento',
    incidencias: [],
    automatico: false,
    ativo: false,
  },
  {
    id: 80,
    codigo: 'D006',
    descricao: 'Fundo de Pensão',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 81,
    codigo: 'P099',
    descricao: 'Premiação por Tempo de Empresa',
    tipo: 'Provento',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 82,
    codigo: 'D099',
    descricao: 'Contribuição Confederativa',
    tipo: 'Desconto',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 83,
    codigo: 'P105',
    descricao: 'Gueltas',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 84,
    codigo: 'P130',
    descricao: 'Abatimento IRRF (Dependentes)',
    tipo: 'Provento',
    incidencias: ['Dedução IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 85,
    codigo: 'D013',
    descricao: 'Contribuição Patronal Previdência',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: false,
  },
  {
    id: 86,
    codigo: 'P600',
    descricao: 'Stock Options Exercidas',
    tipo: 'Provento',
    incidencias: ['IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 87,
    codigo: 'D002',
    descricao: 'INSS sobre 13º Salário',
    tipo: 'Desconto',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 88,
    codigo: 'P700',
    descricao: 'Pro labore',
    tipo: 'Provento',
    incidencias: ['INSS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 89,
    codigo: 'D022',
    descricao: 'Multa de Trânsito (Veículo Empresa)',
    tipo: 'Desconto',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 90,
    codigo: 'P006',
    descricao: 'Diferença de Adicional Noturno',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 91,
    codigo: 'P026',
    descricao: 'Bienio',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 92,
    codigo: 'D035',
    descricao: 'Vale Gás (Desconto)',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 93,
    codigo: 'P031',
    descricao: 'Auxílio Educação',
    tipo: 'Provento',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 94,
    codigo: 'D038',
    descricao: 'Mensalidade Grêmio Recreativo',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
  {
    id: 95,
    codigo: 'P010',
    descricao: 'Gorjetas',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 96,
    codigo: 'D007',
    descricao: 'IRRF sobre 13º Salário',
    tipo: 'Desconto',
    incidencias: [],
    automatico: false,
    ativo: true,
  },
  {
    id: 97,
    codigo: 'P042',
    descricao: 'Adicional de Confinamento',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 98,
    codigo: 'D017',
    descricao: 'Desconto de Horas Negativas',
    tipo: 'Desconto',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: false,
    ativo: true,
  },
  {
    id: 99,
    codigo: 'P048',
    descricao: 'Gratificação por Dirigir Veículo',
    tipo: 'Provento',
    incidencias: ['INSS', 'FGTS', 'IRRF'],
    automatico: true,
    ativo: true,
  },
  {
    id: 100,
    codigo: 'D100',
    descricao: 'Contribuição para o SESC/SENAC',
    tipo: 'Desconto',
    incidencias: [],
    automatico: true,
    ativo: true,
  },
];
